// <auto-generated />
using System;
using BillManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BillManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:Collation", "Romanian_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BillManager.Models.DetaliiFactura", b =>
                {
                    b.Property<int>("IdDetaliiFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdLocatie")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantitate")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<string>("NumeProdus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PretUnitar")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("Valoare")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("IdDetaliiFactura", "IdLocatie");

                    b.HasIndex("IdFactura", "IdLocatie");

                    b.ToTable("DetaliiFacturi");
                });

            modelBuilder.Entity("BillManager.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdLocatie")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFactura")
                        .HasColumnType("date");

                    b.Property<string>("NumarFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFactura", "IdLocatie");

                    b.ToTable("Facturi");
                });

            modelBuilder.Entity("BillManager.Models.DetaliiFactura", b =>
                {
                    b.HasOne("BillManager.Models.Factura", "Factura")
                        .WithMany("DetaliiFactura")
                        .HasForeignKey("IdFactura", "IdLocatie")
                        .HasConstraintName("FK_DetaliiFactura_Facturi")
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("BillManager.Models.Factura", b =>
                {
                    b.Navigation("DetaliiFactura");
                });
#pragma warning restore 612, 618
        }
    }
}
